version: '3.9'
services:
  nacre:
    image: "nacre:latest"
    ports:
      - "8080:8080"
      - "9090:1337"
    environment:
      NACRE_TCP_ADDR: ":1337"   # Matches internal port listed above
      NACRE_HTTP_ADDR: ":8080"  # Matches internal port listed above
      NACRE_BASE_URL: "https://nacre.dev"
      NACRE_MAX_STREAM_LEN: 1000
      NACRE_MAX_STREAM_PERSISTENCE: "24h0m0s"
      NACRE_REDIS_HOST: "redis"
      NACRE_REDIS_PORT: 6379
      NACRE_REDIS_PASSWORD: ""
    depends_on:
      redis:
        condition: service_started

  redis:
    image: "redis:latest"
    expose:
      - "6379"
